=== SonyaStern/vLab/var/input/TestSet.dtd
<?xml version="1.0" encoding="UTF-8"?><!ELEMENT TestConfig (URL, Method, RLCPRequest)><!ELEMENT URL (#PCDATA)><!ELEMENT Method (#PCDATA)><!ELEMENT RLCPRequest (Request)><!ELEMENT Output (#PCDATA)><!ELEMENT Input (#PCDATA)><!ELEMENT Request (Conditions, Instructions?, PreGenerated?)><!ELEMENT Conditions (ConditionForCalculating | ConditionForChecking+ | ConditionForGenerating)><!ELEMENT ConditionForChecking (Input, Output)><!ATTLIST ConditionForChecking	id CDATA #REQUIRED	Time CDATA #REQUIRED><!ELEMENT ConditionForCalculating (Input)><!ATTLIST ConditionForCalculating	Time CDATA #REQUIRED><!ELEMENT ConditionForGenerating (Input)><!ELEMENT Instructions (#PCDATA)><!ELEMENT PreGenerated (Text,Code,Instructions)><!ELEMENT Text (#PCDATA)><!ELEMENT Code (#PCDATA)>

=== SonyaStern/vLab/var/input/generate-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestConfig SYSTEM "TestSet.dtd">
<TestConfig>
    <URL>url:rlcp://user:user@127.0.0.1:3000</URL>
    <Method>GENERATE</Method>
    <RLCPRequest>
        <Request>
            <Conditions>
                <ConditionForGenerating>
                    <Input>
                        <!-- generating cond -->
                    </Input>
                </ConditionForGenerating>
            </Conditions>
        </Request>
    </RLCPRequest>
</TestConfig>

=== SonyaStern/vLab/var/input/calculate-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestConfig SYSTEM "TestSet.dtd">
<TestConfig>
    <URL>url:rlcp://user:user@127.0.0.1:3000</URL>
    <Method>CALCULATE</Method>
    <RLCPRequest>
        <Request>
            <Conditions>
                <ConditionForCalculating Time="500">
                    <Input>
			<!-- тест-тест-тест -->
                    </Input>
                </ConditionForCalculating>
            </Conditions>
            <Instructions>
		<!-- тест-тест-тест2 -->
            </Instructions>
            <PreGenerated>
                <Text>
                    <!-- тест-тест-тест2 -->
                </Text>
                <Code>
                    <!-- тест-тест-тест2 -->
                </Code>
                <Instructions>
                    <!-- тест-тест-тест2 -->
                </Instructions>
            </PreGenerated>
        </Request>
    </RLCPRequest>
</TestConfig>

=== SonyaStern/vLab/var/input/check-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestConfig SYSTEM "TestSet.dtd">
<TestConfig>
    <URL>url:rlcp://user:user@127.0.0.1:3000</URL>
    <Method>CHECK</Method>
    <RLCPRequest>
        <Request>
            <Conditions>
                <ConditionForChecking id="1" Time="5">
                    <Input>
			<!-- тест-тест-тест -->
                    </Input>
                    <Output>
			<!-- тест-тест-тест3 -->
                    </Output>
                </ConditionForChecking>
                <ConditionForChecking id="2" Time="5">
                    <Input>
			<!-- тест-тест-тест2 -->
                    </Input>
                    <Output>
			<!-- тест-тест-тест2 -->
                    </Output>
                </ConditionForChecking>
            </Conditions>
            <Instructions>
		<!-- тест-тест-тест2 -->
            </Instructions>
            <PreGenerated>
                <Text>
                    <!-- тест-тест-тест2 -->
                </Text>
                <Code>
                    <!-- тест-тест-тест2 -->
                </Code>
                <Instructions>
                    <!-- тест-тест-тест2 -->
                </Instructions>
            </PreGenerated>
        </Request>
    </RLCPRequest>
</TestConfig>
